export enum AreaTematica {
    CIENCIAS = "CIENCIAS",
    NATURALEZA = "NATURALEZA",
    HISTORIA = "HISTORIA",
    GEOGRAFIA="GEOGRAFIA",
    MATEMATICAS = "MATEMATICAS",
    FISICA ="FISICA",
    TECNOLOGIA ="TECNOLOGIA",
    MUSICA ="MUSICA",
    DEPORTE ="DEPORTE",
    INFANTIL = "INFANTIL"
}
export enum TipoRecurso {
    LIBRO="LIBRO",
    REVISTA = "REVISTA",
    FICHA="FICHA",
    PELICULA = "PELICULA",
    DOCUMENTAL ="DOCUMENTAL",
    PERIODICO ="PERIODICO",
}